### ISSUE TITLE
能否先把客户端代码上传了?想学习下结构

### ISSUE THREAD

**Issue by iamnewaplayer** [DrDao/OpenMir2#10]
能否先把客户端代码上传了?想学习下结构

**Comment by mirbeta** [comment]
目前阶段不建议去阅读开发中的客户端代码，几乎每天都会迎来一次比较大的改动，目前不熟悉的话建议先看看整个服务端部分。

**Comment by mirbeta** [comment]
服务端代码都不熟悉，客户端就更加难以理解了。

**Comment by krosin** [comment]
呵呵 学习一下 着急拿去卖是么？
