### ISSUE TITLE
数据库提供一份儿呀

### ISSUE THREAD

**Issue by ll903** [DrDao/OpenMir2#13]

**Comment by ll903** [comment]
数据库的物品、技能、怪物表

**Comment by mirbeta** [comment]
数据库文件在[Mir2.sql](https://github.com/mirbeta/OpenMir2/blob/master/Mir2.sql)

**Comment by ll903** [comment]
提供下物品、技能、怪物的数据呀

**Comment by mirbeta** [comment]
刚刚提交了一份最新的数据库，下载最新的Mir2.sql
