### ISSUE TITLE
服务器已经可以稳定开区了？

### ISSUE THREAD

**Issue by iamnewaplayer** [DrDao/OpenMir2#14]
服务器已经可以稳定开区了？

**Comment by mirbeta** [comment]
暂时不能.还有问题没修复和测试,要做的太多了.

**Comment by iamnewaplayer** [comment]
什么时候开始 可以接受PR？ 打算搞这个了 只搞服务器端

**Comment by mirbeta** [comment]
完全开放接受PR....

**Comment by mirbeta** [comment]
大部分问题都已经被修复了，还有些未知问题还没覆盖到，一个人弄精力有限，想法比较多，没法集中去进行修复，如果能提交PR那更好。

**Comment by iamnewaplayer** [comment]
最好能搞个群 或者 邮件 方便沟通统一架构问题 免得 做无用功

**Comment by mirbeta** [comment]
还是来QQ群吧
118300161

**Comment by igofreely** [comment]
群搜不到了

**Comment by mirbeta** [comment]
> 群搜不到了

解散了

**Comment by 625781186** [comment]
> > 群搜不到了
> 
> 解散了

能放个编译完的客户端吗 和版本吗 , 以前在群里没下载 后悔了
