### ISSUE TITLE
请问哪里可以下载到配套的客户端

### ISSUE THREAD

**Issue by gaodayihao** [DrDao/OpenMir2#58]
大佬，请问哪里可以下载到对应这套服务器端的客户端或者对应的登录器。没有客户端调试不了。

机器没有Delphi环境，暂时没去尝试编译客户端

**Comment by gaodayihao** [comment]
搞了个虚拟机，编译了一下，现在没问题了

**Comment by 625781186** [comment]
> 搞了个虚拟机，编译了一下，现在没问题了

能发一份客户端吗
